[tool.black]
line-length = 110
target-version = ["py38", "py39", "py310"]
skip-string-normalization = true

[tool.mypy]
warn_unused_configs = true
disallow_untyped_defs = false
disallow_incomplete_defs = true
check_untyped_defs = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
ignore_missing_imports = true

[tool.isort]
profile = "black"
add_imports = "from __future__ import annotations"

# [tool.pytest.ini_options]
# NOTE: DO NOT specify the [file_or_dir] in order to run doctest and tests respectively.
# addopts = "--cov api --cov-report term-missing --cov-fail-under 80 -vvs"

[tool.pydocstyle]
convention = "numpy"
add-ignore = "D100,D101,D102,D103,D104,D107,D203,D213"
